### ISSUE TITLE
Release v1.0.1

### ISSUE THREAD

**Issue by juanpujol** [Beakyn/gha-format-release-notes#9]
## TODO
- [ ] Update version on package.json
- [ ] Update all project dependencies
- [ ] Update changelog.md
- [ ] Add release to Github and create tag
- [ ] Release application to production
- [ ] Close milestone
